import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../models/game_mode.dart';

/// One-shot sound effects. File names map 1:1 to `assets/audio/<name>.wav`,
/// generated by `tool/generate_audio.py` (see docs/GDD.md SS7).
enum Sfx {
  move,
  rotate,
  mirror,
  softDrop,
  hardDrop,
  lock,
  clear1,
  clear2,
  clear3,
  clearTetris,
  fusionBonus,
  comboTick,
  cavityFill,
  levelUp,
  gameOver,
  newBest,
  menuTap,
  pause,
  danger,
  achievementUnlock,
}

extension on Sfx {
  String get asset => switch (this) {
    Sfx.move => 'move.wav',
    Sfx.rotate => 'rotate.wav',
    Sfx.mirror => 'mirror.wav',
    Sfx.softDrop => 'soft_drop.wav',
    Sfx.hardDrop => 'hard_drop.wav',
    Sfx.lock => 'lock.wav',
    Sfx.clear1 => 'clear_1.wav',
    Sfx.clear2 => 'clear_2.wav',
    Sfx.clear3 => 'clear_3.wav',
    Sfx.clearTetris => 'clear_tetris.wav',
    Sfx.fusionBonus => 'fusion_bonus.wav',
    Sfx.comboTick => 'combo_tick.wav',
    Sfx.cavityFill => 'cavity_fill.wav',
    Sfx.levelUp => 'level_up.wav',
    Sfx.gameOver => 'game_over.wav',
    Sfx.newBest => 'new_best.wav',
    Sfx.menuTap => 'menu_tap.wav',
    Sfx.pause => 'pause.wav',
    Sfx.danger => 'danger.wav',
    Sfx.achievementUnlock => 'achievement_unlock.wav',
  };
}

/// Background music beds. Looping is handled by the player itself.
enum MusicTrack {
  menu('music_menu_loop.wav'),
  marathon('music_marathon_loop.wav'),
  zen('music_zen_loop.wav'),
  arcade('music_arcade_loop.wav');

  const MusicTrack(this.asset);
  final String asset;

  /// Every mode (and the menu) shares Chill's calm ambient bed rather than
  /// switching tracks per mode — one consistent musical identity for the
  /// whole app.
  static MusicTrack forMode(GameMode mode) => MusicTrack.zen;
}

/// Central audio gateway: independent music/SFX volume, a master mute, and
/// settings persisted across launches. Every gameplay event routes through
/// here rather than touching `audioplayers` directly, so callers never need
/// to know whether audio is currently muted or unavailable (e.g. web
/// autoplay policies before the first user gesture).
class AudioService extends ChangeNotifier {
  AudioService(this._prefs) {
    _musicPlayer.setReleaseMode(ReleaseMode.loop);
  }

  static const _keyMuted = 'audio_muted';
  static const _keyMusicVolume = 'audio_music_volume';
  static const _keySfxVolume = 'audio_sfx_volume';

  final SharedPreferences _prefs;
  final AudioPlayer _musicPlayer = AudioPlayer();
  final List<AudioPlayer> _sfxPool = List.generate(4, (_) => AudioPlayer());
  int _sfxPoolIndex = 0;
  MusicTrack? _currentTrack;

  static Future<AudioService> create() async {
    return AudioService(await SharedPreferences.getInstance());
  }

  bool get muted => _prefs.getBool(_keyMuted) ?? false;
  double get musicVolume => _prefs.getDouble(_keyMusicVolume) ?? 0.6;
  double get sfxVolume => _prefs.getDouble(_keySfxVolume) ?? 0.8;

  Future<void> setMuted(bool value) async {
    await _prefs.setBool(_keyMuted, value);
    try {
      await _musicPlayer.setVolume(value ? 0 : musicVolume);
    } catch (_) {
      // Same reasoning as playMusic -- never let audio break gameplay.
    }
    notifyListeners();
  }

  Future<void> setMusicVolume(double value) async {
    await _prefs.setDouble(_keyMusicVolume, value);
    if (!muted) {
      try {
        await _musicPlayer.setVolume(value);
      } catch (_) {
        // Same reasoning as playMusic -- never let audio break gameplay.
      }
    }
    notifyListeners();
  }

  Future<void> setSfxVolume(double value) async {
    await _prefs.setDouble(_keySfxVolume, value);
    notifyListeners();
  }

  Future<void> playMusic(MusicTrack track) async {
    if (_currentTrack == track) return;
    final previousTrack = _currentTrack;
    _currentTrack = track;
    try {
      await _musicPlayer.stop();
      await _musicPlayer.setVolume(muted ? 0 : musicVolume);
      await _musicPlayer.play(AssetSource('audio/${track.asset}'));
    } catch (_) {
      // Autoplay/codec issues (e.g. web before a user gesture) must never
      // crash the game -- audio is enhancement, not a dependency. Roll back
      // so a later retry (e.g. once a user gesture unlocks web autoplay)
      // isn't silently skipped by the guard above.
      _currentTrack = previousTrack;
    }
  }

  Future<void> stopMusic() async {
    _currentTrack = null;
    try {
      await _musicPlayer.stop();
    } catch (_) {}
  }

  Future<void> play(Sfx sfx) async {
    if (muted || sfxVolume <= 0) return;
    final player = _sfxPool[_sfxPoolIndex];
    _sfxPoolIndex = (_sfxPoolIndex + 1) % _sfxPool.length;
    try {
      await player.stop();
      await player.setVolume(sfxVolume);
      await player.play(AssetSource('audio/${sfx.asset}'));
    } catch (_) {
      // Same reasoning as playMusic -- never let sound break gameplay.
    }
  }

  @override
  void dispose() {
    _musicPlayer.dispose();
    for (final p in _sfxPool) {
      p.dispose();
    }
    super.dispose();
  }
}
