import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../models/game_mode.dart';

/// One-shot sound effects. File names map 1:1 to `assets/audio/<name>.wav`,
/// generated by `tool/generate_audio.py` (see docs/GDD.md SS7).
enum Sfx {
  move,
  rotate,
  mirror,
  softDrop,
  hardDrop,
  lock,
  clear1,
  clear2,
  clear3,
  clearFourLine,
  fusionBonus,
  comboTick,
  cavityFill,
  levelUp,
  gameOver,
  newBest,
  menuTap,
  pause,
  danger,
  achievementUnlock,
}

extension SfxAsset on Sfx {
  String get asset => switch (this) {
    Sfx.move => 'move.wav',
    Sfx.rotate => 'rotate.wav',
    Sfx.mirror => 'mirror.wav',
    Sfx.softDrop => 'soft_drop.wav',
    Sfx.hardDrop => 'hard_drop.wav',
    Sfx.lock => 'lock.wav',
    Sfx.clear1 => 'clear_1.wav',
    Sfx.clear2 => 'clear_2.wav',
    Sfx.clear3 => 'clear_3.wav',
    // Keep the legacy filename so existing packaged assets remain compatible.
    Sfx.clearFourLine => 'clear_tetris.wav',
    Sfx.fusionBonus => 'fusion_bonus.wav',
    Sfx.comboTick => 'combo_tick.wav',
    Sfx.cavityFill => 'cavity_fill.wav',
    Sfx.levelUp => 'level_up.wav',
    Sfx.gameOver => 'game_over.wav',
    Sfx.newBest => 'new_best.wav',
    Sfx.menuTap => 'menu_tap.wav',
    Sfx.pause => 'pause.wav',
    Sfx.danger => 'danger.wav',
    Sfx.achievementUnlock => 'achievement_unlock.wav',
  };
}

/// Background music beds. Looping is handled by the player itself.
enum MusicTrack {
  menu('tmusic.mp3'),
  gameplay('zen_classic_arcade_music.mp3');

  const MusicTrack(this.asset);
  final String asset;

  /// Every gameplay mode shares the supplied gameplay loop. Menu and
  /// room-waiting screens use [MusicTrack.menu] instead.
  static MusicTrack forMode(GameMode mode) => MusicTrack.gameplay;
}

/// Central audio gateway: independent music/SFX volume, a master mute, and
/// settings persisted across launches. Every gameplay event routes through
/// here rather than touching `audioplayers` directly, so callers never need
/// to know whether audio is currently muted or unavailable (e.g. web
/// autoplay policies before the first user gesture).
class AudioService extends ChangeNotifier {
  AudioService(this._prefs);

  static const double defaultMusicVolume = 0.25;
  static const double defaultSfxVolume = 0.9;

  static const _keyMuted = 'audio_muted';
  static const _keyMusicVolume = 'audio_music_volume';
  static const _keySfxVolume = 'audio_sfx_volume';

  final SharedPreferences _prefs;
  final AudioPlayer _musicPlayer = AudioPlayer();
  // A few effects can legitimately overlap (hard drop + lock + line clear),
  // especially when both cooperative players act at nearly the same time.
  final List<AudioPlayer> _sfxPool = List.generate(6, (_) => AudioPlayer());
  int _sfxPoolIndex = 0;
  MusicTrack? _currentTrack;
  int _musicRequest = 0;
  Future<void> _musicOperation = Future.value();

  static Future<AudioService> create() async {
    final service = AudioService(await SharedPreferences.getInstance());
    // Player setup and caching must never delay the first frame. In
    // particular, plugin channels are unavailable in widget tests and can be
    // slow to initialize on the web; play() remains able to load on demand.
    unawaited(service._initializePlayers());
    return service;
  }

  Future<void> _initializePlayers() async {
    try {
      await _musicPlayer.setReleaseMode(ReleaseMode.loop);
    } catch (_) {
      // Audio is optional on unsupported test targets and before web unlocks.
    }
    for (final player in _sfxPool) {
      try {
        await player.setReleaseMode(ReleaseMode.stop);
        await player.setPlayerMode(PlayerMode.lowLatency);
      } catch (_) {
        // Low-latency mode is not implemented on every platform.
      }
    }
    // Decode/cache the short effects once so the first move or clear does not
    // pay asset-loading latency. Failure remains non-fatal, as play() can load
    // an individual effect on demand later.
    try {
      await AudioCache.instance.loadAll([
        for (final sfx in Sfx.values) 'audio/${sfx.asset}',
      ]);
    } catch (_) {}
  }

  bool get muted => _prefs.getBool(_keyMuted) ?? false;
  double get musicVolume =>
      _prefs.getDouble(_keyMusicVolume) ?? defaultMusicVolume;
  double get sfxVolume => _prefs.getDouble(_keySfxVolume) ?? defaultSfxVolume;

  Future<void> setMuted(bool value) async {
    await _prefs.setBool(_keyMuted, value);
    // Update every visible mute button as soon as the persisted state lands;
    // a platform audio call may complete later (or fail on an unsupported
    // test/web codec) and should never make the HUD feel unresponsive.
    notifyListeners();
    try {
      await _musicPlayer.setVolume(value ? 0 : musicVolume);
    } catch (_) {
      // Same reasoning as playMusic -- never let audio break gameplay.
    }
  }

  Future<void> setMusicVolume(double value) async {
    await _prefs.setDouble(_keyMusicVolume, value);
    // Repaint sliders as soon as persistence succeeds. Platform audio calls
    // may complete later on web or be unavailable in tests, but neither
    // should make the visible percentage lag behind the player's drag.
    notifyListeners();
    if (!muted) {
      try {
        await _musicPlayer.setVolume(value);
      } catch (_) {
        // Same reasoning as playMusic -- never let audio break gameplay.
      }
    }
  }

  Future<void> setSfxVolume(double value) async {
    await _prefs.setDouble(_keySfxVolume, value);
    notifyListeners();
  }

  Future<void> playMusic(MusicTrack track) {
    if (_currentTrack == track) return Future.value();
    final request = ++_musicRequest;
    final previousTrack = _currentTrack;
    _currentTrack = track;
    return _musicOperation = _musicOperation.then((_) async {
      // Skip stale requests before they touch the player. Serializing these
      // operations prevents a slow old stop() from silencing a newer route's
      // track after rapid menu -> game navigation.
      if (request != _musicRequest) return;
      try {
        await _musicPlayer.stop();
        if (request != _musicRequest) return;
        await _musicPlayer.setVolume(muted ? 0 : musicVolume);
        if (request != _musicRequest) return;
        await _musicPlayer.play(AssetSource('audio/${track.asset}'));
      } catch (_) {
        // Autoplay/codec issues (e.g. web before a user gesture) must never
        // crash the game. Roll back so a later retry isn't silently skipped.
        if (request == _musicRequest) _currentTrack = previousTrack;
      }
    });
  }

  Future<void> stopMusic() {
    final request = ++_musicRequest;
    _currentTrack = null;
    return _musicOperation = _musicOperation.then((_) async {
      if (request != _musicRequest) return;
      try {
        await _musicPlayer.stop();
      } catch (_) {}
    });
  }

  /// Pauses the music bed without forgetting the current track (unlike
  /// [stopMusic]) -- meant for the app going into the background, where
  /// nothing else would ever stop it otherwise (see [_HalfBlockPyramidApp]'s
  /// lifecycle observer). Route changes may swap tracks, but neither should
  /// continue playing (and draining battery) while the app isn't in front.
  Future<void> pauseMusic() async {
    try {
      await _musicPlayer.pause();
    } catch (_) {}
  }

  /// Resumes music paused by [pauseMusic] -- a no-op if nothing was playing
  /// to begin with (e.g. still muted, or before the first user gesture on
  /// web unlocks autoplay).
  Future<void> resumeMusic() async {
    if (_currentTrack == null) return;
    try {
      await _musicPlayer.resume();
    } catch (_) {}
  }

  Future<void> play(Sfx sfx) async {
    if (muted || sfxVolume <= 0) return;
    final player = _sfxPool[_sfxPoolIndex];
    _sfxPoolIndex = (_sfxPoolIndex + 1) % _sfxPool.length;
    try {
      await player.stop();
      await player.setVolume(sfxVolume);
      await player.play(AssetSource('audio/${sfx.asset}'));
    } catch (_) {
      // Same reasoning as playMusic -- never let sound break gameplay.
    }
  }

  @override
  void dispose() {
    _musicPlayer.dispose();
    for (final p in _sfxPool) {
      p.dispose();
    }
    super.dispose();
  }
}
